import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Button } from '@/components/ui/button';
import { SidebarButton } from '@/components/sidebar-button';
import { SidebarGroup } from '@/components/sidebar-group';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="ko">
      <body className={`h-full ${inter.className}`}>
        <h1 className="text-3xl font-black m-6">
          HENEIN <span className="font-normal">SATTO</span>
        </h1>
        <div className="h-full grid grid-cols-5">
          <div className="col-span-1 flex flex-col p-2 space-y-1">
            <SidebarButton href="/">홈</SidebarButton>
            <SidebarGroup title="조회">
              <SidebarButton href="/user">유저</SidebarButton>
              <SidebarButton href="/character">캐릭터</SidebarButton>
              <SidebarButton href="/post">게시글</SidebarButton>
              <SidebarButton href="/comment">댓글</SidebarButton>
            </SidebarGroup>
            <SidebarGroup title="변경">
              <SidebarButton href="/notice">공지</SidebarButton>
              <SidebarButton href="/category">게시판</SidebarButton>
            </SidebarGroup>
            <SidebarGroup title="신고">
              <SidebarButton href="/report-post">게시글</SidebarButton>
              <SidebarButton href="/report-comment">댓글</SidebarButton>
            </SidebarGroup>
          </div>
          <div className="px-4 col-span-4 border-l space-y-4">
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
